import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Footer } from "@/components/Footer";
// import { Providers } from "@/components/Providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="container max-w-[1600px] m-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
